'use client';

import ProgramsHero from '../components/ProgramsHero';
import ProgramCards from '../components/ProgramCards';

export default function ProgramsPage() {
  const allPrograms = [
    {
      id: 1,
      name: 'BA (Hons) Business and Management',
      slug: 'ba-business-management',
      level: 'Undergraduate',
      category: 'Business',
      duration: '1, 2, 3, or 4 years',
      accreditation: 'AACSB Accredited',
      image: '/hons.webp',
      description: 'Develop the skills and knowledge to lead in today\'s competitive business world. Gain expertise in leadership, marketing, finance, and strategic planning.',
    },
    {
      id: 2,
      name: 'BSc (Hons) Cyber Security',
      slug: 'bsc-cyber-security',
      level: 'Undergraduate',
      category: 'Technology',
      duration: '2, 3, or 4 years',
      accreditation: 'NCSC Certified',
      image: '/cyber.webp',
      description: 'Protect the digital world with hands-on skills in ethical hacking, network security, risk management, and digital forensics.',
    },
    {
      id: 3,
      name: 'BSc (Hons) Accounting and Finance',
      slug: 'bsc-accounting-finance',
      level: 'Undergraduate',
      category: 'Business',
      duration: '2 or 4 years',
      accreditation: 'ACCA Recognized',
      image: '/accouting.webp',
      description: 'Build a strong foundation for a successful career in finance. Learn financial management, auditing, taxation, and investment analysis.',
    },
    {
      id: 4,
      name: 'BSc (Hons) Health and Social Care',
      slug: 'bsc-health-social-care',
      level: 'Undergraduate',
      category: 'Health',
      duration: '1, 2, 3, or 4 years',
      accreditation: 'QAA Approved',
      image: '/health.webp',
      description: 'Prepare for a rewarding career supporting individuals and communities. Gain practical skills in care, safeguarding, and health systems.',
    },
    {
      id: 5,
      name: 'BSc Computer Science',
      slug: 'bsc-computer-science',
      level: 'Undergraduate',
      category: 'Technology',
      duration: '3 or 4 years',
      accreditation: 'BCS Accredited',
      image: '/computer.webp',
      description: 'Build a future in tech. Learn core skills in programming, networking, cybersecurity, and software development.',
    },
    {
      id: 6,
      name: 'BSc (Hons) Data Science',
      slug: 'bsc-data-science',
      level: 'Undergraduate',
      category: 'Technology',
      duration: '3 or 4 years',
      accreditation: 'QAA Approved',
      image: '/data science.webp',
      description: 'Turn data into insight. Develop expertise in data analysis, programming, statistics, and machine learning.',
    },
    {
      id: 7,
      name: 'BSc Psychology',
      slug: 'bsc-psychology',
      level: 'Undergraduate',
      category: 'Psychology',
      duration: '3 or 4 years',
      accreditation: 'BPS Accredited',
      image: '/pycholgy.webp',
      description: 'Explore the science of the mind and human behavior. Gain a deep understanding of cognitive, social, developmental, and clinical psychology.',
    },
    {
      id: 8,
      name: 'BA (Hons) Criminology and Psychology',
      slug: 'ba-criminology-psychology',
      level: 'Undergraduate',
      category: 'Psychology',
      duration: '3 or 4 years',
      accreditation: 'QAA Approved',
      image: '/criminology.webp',
      description: 'Explore the relationship between crime, behavior, and society combined with the scientific study of the mind.',
    },
    {
      id: 9,
      name: 'LLB (Hons) Law',
      slug: 'llb-law',
      level: 'Undergraduate',
      category: 'Law',
      duration: '3 or 4 years',
      accreditation: 'SRA Recognized',
      image: '/llb.webp',
      description: 'Gain a solid foundation in legal knowledge and critical thinking. Covers criminal law, contract law, constitutional law, and human rights.',
    },
    {
      id: 10,
      name: 'BSc (Hons) International Hospitality and Tourism Management',
      slug: 'bsc-hospitality-tourism',
      level: 'Undergraduate',
      category: 'Hospitality',
      duration: '3 or 4 years',
      accreditation: 'QAA Approved',
      image: '/international.webp',
      description: 'Discover the dynamic world of global hospitality and tourism. Combines business management with practical industry insights.',
    },
    {
      id: 11,
      name: 'BSc (Hons) Digital Marketing',
      slug: 'bsc-digital-marketing',
      level: 'Undergraduate',
      category: 'Business',
      duration: '3 or 4 years',
      accreditation: 'CIM Recognized',
      image: '/digital marketing.webp',
      description: 'Master the art of online engagement. Covers social media marketing, SEO, analytics, branding, and digital advertising.',
    },
    {
      id: 12,
      name: 'BSc (Hons) Project Management',
      slug: 'bsc-project-management',
      level: 'Undergraduate',
      category: 'Business',
      duration: '3 or 4 years',
      accreditation: 'APM Recognized',
      image: '/project.webp',
      description: 'Develop the skills to lead projects across industries. Learn planning, risk management, budgeting, and Agile methodology.',
    },
  ];

  return (
    <div>
      <ProgramsHero />
      <ProgramCards programs={allPrograms} />
    </div>
  );
}